#!/bin/bash

DATADIR="$(cd $(dirname $0)/../data ; pwd)"

echo "#!/bin/bash"                                                   > $1
echo "# Generated by $(basename $0)"                                >> $1
echo                                                                >> $1
echo "if test \"\$1\" = \"--help\" || test \"\$1\" = \"-h\" ||"     >> $1
echo "   test \"\$1\" = \"\" ; then"                                >> $1
echo "  echo \"Usage: ./run.sh <executable> [parameters] ...\""     >> $1
echo "  exit"                                                       >> $1
echo "fi"                                                           >> $1
echo                                                                >> $1
echo "if test \"\$FREECIV_DATA_PATH\" = \"\" ; then"                >> $1
echo "  export FREECIV_DATA_PATH=\"$DATADIR\""                      >> $1
echo "else"                                                         >> $1
echo "  export FREECIV_DATA_PATH=\"\$FREECIV_DATA_PATH:$DATADIR\""  >> $1
echo "fi"                                                           >> $1
echo                                                                >> $1
echo "./\$@"                                                        >> $1

chmod +x $1
