#!/bin/sh
#/********************************************************************** 
# Freeciv - Copyright (C) 1996 - A Kjeldberg, L Gregersen, P Unold
# script by Rene Schalburg
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2, or (at your option)
#   any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#***********************************************************************/
DIR=`dirname $0`

#if [ "$FREECIV_DATADIR" = "" ] ; then
#    FREECIV_DATADIR=$DIR/data; export FREECIV_DATADIR
#fi

[ -x $DIR/server/civserver ] && EXE=$DIR/server/civserver
[ -x $DIR/civserver ] && EXE=$DIR/civserver

if [ "$EXE" = "" ]; then
  echo $0: Unable to find civserver.
  exit 1
fi

exec $EXE ${1+"$@"}
