/**
 * Barrel for the agent-side (`full-control-v2`) wire vocabulary.
 *
 * These are the packets an *agent* exchanges with the supervisor — the
 * protocol `play/client.py` speaks — as opposed to the read-only replay-gateway
 * payloads in `../gateway/index.ts`.  The two halves share `../canon.ts`,
 * `../json.ts`, `../tolerant.ts` and `../control-protocol.ts`, and nothing
 * else.
 *
 * Reached as `Agent` from the package barrel: `Wire.Agent.decodeReceipt`.
 * Where the two halves name the same concept differently the difference is
 * real and is documented at the definition, and the namespace is what keeps
 * both spellings reachable:
 *
 *   - `Agent.PlayGameId` is a different regex from `GameId` (the gateway's).
 *   - **`Agent.WireInt` is not `WireInt`.**  The agent protocol's integers are
 *     counters the port does arithmetic on, so they stay `number`-spelled and
 *     cross into `bigint` at the hashing boundary — see `revisionCanonRecord`
 *     in `./revision.ts`, and the "deliberate namesake" section of
 *     `../numeric.ts`.  A decoded agent integer is a `number`; a decoded
 *     gateway integer is a `bigint`.  That is on purpose.
 *
 * Names are listed rather than `export *`-ed so that the public surface is a
 * written artifact: adding a module export does not silently widen the
 * package's API, and a reviewer can see the whole of it in one file.
 *
 * @module
 */

export {
  ACTOR_ID_RE,
  ACTOR_TYPES,
  ActorId,
  ActorType,
  ALIAS_ENTITY_TYPES,
  type AliasEntityKind,
  type AliasPrefix,
  CATALOG_RE,
  CatalogId,
  CITY_ID_RE,
  CityId,
  CONTROLLER_RE,
  ControllerLabel,
  ControllerName,
  Cursor,
  CURSOR_RE,
  decodeActorId,
  decodeActorType,
  decodeCatalogId,
  decodeCityId,
  decodeControllerName,
  decodeCursor,
  decodeEntityAlias,
  decodeOpaqueId,
  decodePlayGameId,
  decodeRelationId,
  decodeTileId,
  ENTITY_ALIAS_RE,
  EntityAlias,
  entityAliasIdMatches,
  idPrefix,
  isActorId,
  isActorType,
  isCatalogId,
  isCityId,
  isControllerName,
  isCursor,
  isOpaqueId,
  isPlayGameId,
  isRelationId,
  isTileId,
  OPAQUE_ID_RE,
  OpaqueId,
  PLAY_GAME_ID_RE,
  PlayGameId,
  RELATION_ID_RE,
  RelationId,
  TILE_ID_RE,
  TileId,
} from './ids.ts';

export {
  boundedJson,
  BoundedJsonObject,
  boundedJsonObject,
  BoundedJsonValue,
  boundedText,
  checkEvaluationDrift,
  codePointLength,
  decodeBoundedJsonObject,
  decodeBoundedJsonValue,
  decodeEvaluationContext,
  decodeEvaluationSlot,
  decodeNullableSafeNumber,
  decodeSafeNumber,
  decodeSessionIdentity,
  driftError,
  EvaluationContext,
  type EvaluationSlotOptions,
  exactFields,
  type FieldDrift,
  fieldDrift,
  formatFieldDrift,
  hasOwnKey,
  isExactMatch,
  isRecord,
  JSON_MAX_DEPTH,
  JSON_MAX_ITEMS,
  JSON_MAX_KEY_LENGTH,
  JSON_MAX_KEYS,
  jsonNodeDepth,
  MAX_TURNS_CEILING,
  NonEmptyText,
  NonNegativeWireInt,
  NullableSafeNumber,
  PositiveWireInt,
  SafeNumber,
  safeNumber,
  type SafeNumberOptions,
  SessionIdentity,
  sortedNames,
  type UnknownRecord,
  V2_EVALUATION_FIELDS,
  WireInt,
} from './primitives.ts';

export {
  ControlProtocolV2,
  decodeV2JsonObject,
  FULL_CONTROL_V2,
  SCHEMA_VERSION_V2,
  SchemaVersionV2,
  sessionMismatch,
  STRATEGIC_V1,
  type V2Addressed,
  V2JsonObject,
  type V2Session,
} from './protocol.ts';

export {
  compareRevisions,
  decodeRevision,
  decodeRevisionExact,
  Revision,
  REVISION_FIELDS,
  revisionCanonRecord,
  RevisionCounter,
  revisionOrder,
  revisionsEqual,
  StateRevision,
} from './revision.ts';

export {
  ACTION_OUTCOME_AMBIGUOUS,
  decodeError,
  ERROR_MESSAGE_MAX,
  errorMessageText,
  StructuredError,
  StructuredErrorBody,
  type StructuredErrorEncoded,
  V2_ERROR_CODES,
  V2ErrorCode,
  V2ErrorMessage,
  v2ErrorMessage,
} from './error.ts';

export {
  ACTION_KIND_RE,
  ActionKind,
  decodeActionKind,
  decodeDescriptorAt,
  decodeLegalActionDescriptor,
  DESCRIPTOR_LABEL_MAX,
  DescriptorLabel,
  descriptorLabelText,
  isActionKind,
  LegalActionDescriptor,
  legalActionDescriptorAt,
  type LegalActionDescriptorEncoded,
} from './descriptor.ts';

export {
  type CityFeeling,
  CityFeelings,
  CityImprovement,
  CityImprovements,
  CityInvestigationObservation,
  type CityInvestigationObservationEncoded,
  CityProduction,
  CityShields,
  CitySpecialist,
  CitySpecialists,
  decodeInvestigation,
  decodeInvestigationAt,
  FEELING_STAGES,
  feelingPopulation,
  type FeelingStage,
  IMPROVEMENTS_MAX,
  InvestigatedCity,
  investigationAt,
  MOOD_KEYS,
  specialistPopulation,
  SPECIALISTS_MAX,
} from './observation.ts';

export {
  catalogCompleteFor,
  CURSOR_EXPIRY_RE,
  CursorExpiry,
  cursorExpiryMillis,
  decodeCursorExpiry,
  decodePageScope,
  decodeStatePage,
  decodeStatePageFor,
  encodeStatePage,
  legacyCatalogId,
  legacyCatalogSeed,
  pageBodyCatalogFields,
  pageBodyIssues,
  pageBodyPaginationFields,
  type PageBodyShape,
  PageCount,
  pageCursorExpiry,
  PageScope,
  type PageScopeEncoded,
  StatePageBody,
  StatePageEnvelope,
  type StatePageEnvelopeEncoded,
  statePageFor,
  StatePageSection,
  V2_PAGE_MAX_ITEMS,
  V2_SECTIONS,
  v2PageHeaderFields,
} from './page.ts';

export {
  decodeLegalPage,
  decodeLegalPageFor,
  encodeLegalPage,
  LEGAL_ACTIONS_SECTION,
  LegalActionPageBody,
  LegalActionPageEnvelope,
  type LegalActionPageEnvelopeEncoded,
  LegalActionsSection,
  legalPageFor,
  scopesEqual,
} from './legal-page.ts';

export {
  carriesError,
  CommandReceipt,
  type CommandReceiptEncoded,
  commandReceiptFor,
  decodeReceipt,
  decodeReceiptFor,
  isTerminalReceiptState,
  type ReceiptOptions,
  ReceiptState,
  V2_RECEIPT_STATES,
  V2_TERMINAL_RECEIPTS,
} from './receipt.ts';

export {
  BatchDisposition,
  type BatchDispositionEncoded,
  batchDispositionFor,
  Command,
  CommandBatch,
  type CommandBatchEncoded,
  commandBatchFor,
  COMMANDS_PER_BATCH,
  decodeBatchDisposition,
  decodeBatchDispositionFor,
  decodeCommand,
  decodeCommandBatch,
  decodeCommandBatchFor,
  Disposition,
  V2_DISPOSITIONS,
} from './batch.ts';

export {
  decodeWait,
  decodeWaitFor,
  isSatisfiedWake,
  V2_SATISFIED_WAKE_REASONS,
  V2_WAKE_REASONS,
  WAIT_UNTILS,
  type WaitContract,
  WaitEnvelope,
  type WaitEnvelopeEncoded,
  waitEnvelopeFor,
  type WaitUntil,
  WakeReason,
} from './wait.ts';

export {
  AutoEnd,
  AWAITING_AGENT,
  decodeHealth,
  decodeHealthFor,
  decodePhaseEndEvent,
  decodeRecoveryEvent,
  evaluationArity,
  HealthAgent,
  HealthEnvelope,
  type HealthEnvelopeEncoded,
  healthEnvelopeFor,
  HealthSeat,
  inlineEvaluation,
  inlineEvaluationIssues,
  isTerminalGameState,
  OptionalEvaluationFields,
  type PartialEvaluation,
  PHASE_END_RECEIPT_STATES,
  PHASE_END_RESOLUTIONS,
  PHASE_END_SOURCES,
  PhaseBlock,
  PhaseEndEvent,
  PhaseEndReceiptState,
  PhaseEndResolution,
  PhaseEndSource,
  PhaseTiming,
  PLAYER_COLOR_RE,
  PlayerColor,
  PriorEnd,
  RecoveryEvent,
  RecoveryKind,
  RecoveryOutcome,
  SEAT_STANDINGS,
  SeatStanding,
  SidecarBlock,
  SidecarValue,
  TimingMode,
  unexpectedSidecarFields,
  V2_GAME_STATES,
  V2_PHASE_STATES,
  V2_RECOVERY_FIELDS,
  V2_RECOVERY_KINDS,
  V2_RECOVERY_OUTCOMES,
  V2_SIDECAR_FIELDS,
  V2_TERMINAL_GAME_STATES,
  V2_TIMING_MODES,
  V2GameState,
  V2PhaseState,
  WAITING_ON_KINDS,
  WaitingOn,
  WaitingOnKind,
  WaitingOnSeat,
} from './health.ts';

