/**
 * Barrel for the replay gateway's read-only payloads.
 *
 * These are the documents `agent_eval/replay_gateway.py` serves and the four
 * on-disk files it serves them from — the half of the protocol a *spectator*
 * sees.  The other half, the packets an agent exchanges with the supervisor,
 * is `../agent/index.ts`; the two share `../canon.ts`, `../json.ts`,
 * `../numeric.ts`, `../tolerant.ts` and the vocabularies in `../ids.ts` and
 * `../control-protocol.ts`, and nothing else.
 *
 * Reached as `Gateway` from the package barrel: `Wire.Gateway.decodeManifest`.
 * The namespace is not decoration — `Manifest`, `GameStatus` and `TimingMode`
 * are only unambiguous next to the word `Gateway`, since the agent half names
 * some of the same concepts differently and one of them (`WireInt`) the same
 * way with a different meaning.  See `../numeric.ts`.
 *
 * Names are listed rather than `export *`-ed so that the public surface is a
 * written artifact: adding a module export does not silently widen the
 * package's API, and a reviewer can see the whole of it in one file.
 *
 * @module
 */

export {
  decodeGatewayIdentity,
  decodeGatewayIdentityToken,
  decodeServiceUrl,
  encodeGatewayIdentity,
  GATEWAY_IDENTITY_RE,
  GATEWAY_IDENTITY_SCHEMA_VERSION,
  GATEWAY_KIND,
  GATEWAY_PROTOCOL_VERSION,
  GATEWAY_SELF_URL_RE,
  GatewayIdentity,
  gatewayIdentityMaterial,
  GatewayIdentityToken,
  GatewayPath,
  GatewayPid,
  GatewayPort,
  GatewaySelfUrl,
  gatewaySelfUrl,
  gatewaySelfUrlMatches,
  isGatewayIdentity,
  isGatewaySelfUrl,
  isNormalizedServiceUrl,
  isSupportedGatewayProtocol,
  ServiceUrl,
} from './identity.ts';

export {
  AiDifficulty,
  ARCHIVE_ERROR_MESSAGE,
  ARCHIVE_OUTCOME_STATUSES,
  ArchiveResult,
  ArchiveUrls,
  ArtifactUrls,
  asInterruptedRow,
  decodeArchiveResult,
  decodeGamePlace,
  decodeGameResult,
  decodeGameRow,
  decodeGamesIndexResponse,
  hasJointTiming,
  timingPairIssue,
  decodeGameStatus,
  decodeInterruptedGameRow,
  decodeLeaderboardEntry,
  decodeMatchOutcome,
  decodeMatchOutcomeStatus,
  decodeMatchOutcomeStatusTolerant,
  decodeMatchVictory,
  decodeUpstreamResult,
  DEFAULT_OBJECTIVE,
  DISK_ROW_OUTCOME_STATUSES,
  encodeArchiveResult,
  encodeGameResult,
  encodeGameRow,
  encodeGamesIndexResponse,
  encodeGameStatus,
  encodeInterruptedGameRow,
  encodeUpstreamResult,
  EXTERNAL_CONTROLLER_TYPE,
  GamePlace,
  GameResult,
  GameRow,
  GamesIndexResponse,
  GameStatus,
  INTERRUPTED_STATUS,
  InterruptedGameRow,
  interruptedOutcome,
  interruptedSummary,
  isAiDifficulty,
  isInterruptedGameRow,
  isInterruptedRow,
  isKnownOutcomeStatus,
  isPublicScoreMetric,
  isTimingMode,
  isUpstreamResult,
  LeaderboardEntry,
  MATCH_OUTCOME_STATUSES,
  MatchOutcome,
  MatchOutcomeStatus,
  MatchOutcomeStatusTolerant,
  MatchVictory,
  NATIVE_CONTROLLER,
  NATIVE_CONTROLLER_LABEL,
  NATIVE_CONTROLLER_MODEL,
  NATIVE_CONTROLLER_TYPE,
  PUBLIC_AI_DIFFICULTY_LEVELS,
  PUBLIC_CONTROL_PROTOCOLS,
  PUBLIC_SCORE_METRICS,
  PUBLIC_TIMING_MODES,
  PublicScoreMetric,
  REDACTED_INVALID_REASON,
  ResultPlayer,
  ResultScore,
  SchemaVersion1,
  ScoreMetrics,
  TimingMode,
  UNCLAIMED_CONTROLLER_LABEL,
  UnrecognizedOutcomeStatus,
  UPSTREAM_OUTCOME_STATUSES,
  UpstreamResult,
} from './games.ts';

export {
  AI_DIFFICULTY_LEVELS,
  ControlProtocolTolerant,
  decodeManifest,
  decodeReplayCatalog,
  decodeReport,
  decodeVictoryRecord,
  EmptyManifest,
  encodeManifest,
  encodeReplayCatalog,
  encodeReport,
  encodeVictoryRecord,
  GAME_MODES,
  Manifest,
  MANIFEST_TIMING_MODES,
  ManifestConfig,
  ManifestSeatConfig,
  ManifestServerConfig,
  MAX_TECHNOLOGY_ID,
  PLACE_CONTROLLERS,
  RecoverySummary,
  ReplayCatalog,
  Report,
  ResolvedPlace,
  Score,
  ScorePlayer,
  SEAT_TYPES,
  SeatStats,
  TechnologyEntry,
  UnrecognizedControlProtocol,
  VICTORY_LABELS,
  type VictoryCode,
  victoryLabel,
  VictoryRecord,
} from './manifest.ts';

export {
  ARCHIVE_BINARY_CACHE_CONTROL,
  ARCHIVE_FRAME_CONTENT_TYPE,
  ARCHIVE_FRAMES_DIRECTORY,
  ARCHIVE_PNG_RE,
  ARCHIVE_PPM_RE,
  ARCHIVE_SAVES_DIRECTORY,
  ARCHIVE_SCHEMA_VERSION,
  ARCHIVE_VIDEO_CONTENT_TYPE,
  ARCHIVE_VIDEO_FILE,
  archiveBinaryContentType,
  type ArchiveBinaryKind,
  ARCHIVED_VIDEO_KIND,
  archiveFramePngPath,
  archiveFramesPath,
  archiveLatestFramePath,
  ArchivePngName,
  archivePpmTurn,
  archiveVideoPath,
  archiveWatchJsonPath,
  decodeArchivePngName,
  decodeFrameManifest,
  decodeMapPlayer,
  decodeReplayFrame,
  encodeReplayFrame,
  decodeTurnTimelineEntry,
  decodeWatchResponse,
  DYNAMIC_CONTROLLER_LABEL,
  DYNAMIC_CONTROLLER_TYPE,
  DYNAMIC_SEAT_ID_PREFIX,
  encodeArchivePngName,
  encodeFrameManifest,
  encodeWatchResponse,
  FRAME_MANIFEST_LABEL,
  FrameManifest,
  isDynamicMapPlayer,
  LEGACY_FRAME_TURN_RE,
  legacyFrameTurn,
  LIVE_VIDEO_KIND,
  MAP_PLAYER_COLOR_RE,
  MapPlayer,
  ReplayFrame,
  SUPERVISOR_FRAME_TURN_RE,
  TurnTimelineEntry,
  WATCH_LABEL,
  type WatchProducer,
  watchProducer,
  WatchReplayLink,
  WatchResponse,
  WatchVideoLink,
} from './archive.ts';

export {
  BOARD_ROUTE_PROBLEMS,
  BoardCity,
  BoardExtra,
  BoardPlayer,
  BoardQuery,
  BoardResponse,
  BoardTerrain,
  BoardUnitStack,
  BoardUnitType,
  decodeBoardQuery,
  decodeBoardResponse,
  decodeGameEvent,
  decodeGameEventsResponse,
  decodeReplayQuery,
  decodeReplayResponse,
  decodeReplaySnapshot,
  decodeReplayWarning,
  decodeResearchState,
  decodeTechnologyCatalog,
  encodeBoardResponse,
  encodeGameEventsResponse,
  encodeReplayResponse,
  encodeTechnologyCatalog,
  EVENTS_ROUTE_PROBLEMS,
  formatBoardQuery,
  formatReplayQuery,
  GAME_EVENT_ACTOR_MAX_LENGTH,
  GAME_EVENT_ACTORS_MAX,
  GAME_EVENT_KIND_MAX_LENGTH,
  GAME_EVENT_MAX_WEIGHT,
  GAME_EVENT_MIN_WEIGHT,
  GAME_EVENT_SUMMARY_MAX_LENGTH,
  GAME_EVENT_WARNING_MESSAGE_MAX_LENGTH,
  GAME_EVENT_WARNINGS_MAX,
  GameEvent,
  GameEventsResponse,
  nextReplayQuery,
  REPLAY_DEFAULT_AFTER_TURN,
  REPLAY_DEFAULT_LIMIT,
  REPLAY_MAX_LIMIT,
  REPLAY_MIN_LIMIT,
  REPLAY_ROUTE_PROBLEMS,
  ReplayPlayer,
  ReplayQuery,
  ReplayResponse,
  ReplaySnapshot,
  ReplayWarning,
  ResearchState,
  Technology,
  TechnologyCatalog,
} from './replay.ts';

export {
  ARCHIVE_JSON_LABELS,
  type ArchiveJsonLabel,
  archiveJsonNotFound,
  archiveJsonUnavailable,
  classifyGatewayProblemMessage,
  decodeGatewayProblem,
  decodeGatewayProblemFromString,
  encodeGatewayProblem,
  GATEWAY_METHOD_NOT_ALLOWED_ALLOW,
  GATEWAY_PROBLEM_CACHE_CONTROL,
  GATEWAY_PROBLEM_CONTENT_TYPE,
  GATEWAY_PROBLEM_MESSAGES,
  GATEWAY_PROBLEM_STATUS,
  GatewayProblem,
  gatewayProblemBody,
  gatewayProblemBytes,
  type GatewayProblemClass,
  GatewayProblemFromString,
  type GatewayProblemMessage,
  type GatewayProblemName,
  type GatewayProblemResponse,
  isBareGatewayProblem,
  isGatewayProblem,
  isKnownGatewayProblemMessage,
  parseUpstreamHttpStatus,
  UPSTREAM_STATUS_MESSAGE_RE,
  upstreamProblem,
  upstreamReturnedHttp,
} from './problem.ts';

