.\" Freeciv - Copyright (C) 1996 - A Kjeldberg, L Gregersen, P Unold
.\"   This program is free software; you can redistribute it and/or modify
.\"   it under the terms of the GNU General Public License as published by
.\"   the Free Software Foundation; either version 2, or (at your option)
.\"   any later version.
.\"
.\"   This program is distributed in the hope that it will be useful,
.\"   but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"   GNU General Public License for more details.
.\"
.TH FREECIV 6 "December 1997"
.SH NAME
civclient \- The client for the Freeciv game
.SH SYNOPSIS
.B civclient
[
.I \-options
]
[
.I \-toolkitoptions
] 

.SH DESCRIPTION
Freeciv is a turn-based strategy game, in which each player becomes
leader of a civilization, fighting to obtain the ultimate goal:
The extinction of all other civilizations.

This is the client program used to connect to a Freeciv server - See also
.IR civserver (6)
.PP
This manpage currently isn't supported by the
.B Freeciv
authors anymore, and
may be outdated or inaccurated. If you are a competent and accurate writer
and are willing to spend the time writing good manpages, if you have the
necessary knowledge about
.B Freeciv
(you may even have to read source code sometimes, but the development
community in the
.I freeciv-dev
mailing list will surely support you) please write a better man page than
this one. You may write other kinds of documentation too - a info manual
( written in
.B texinfo
or
.B linuxdoc-sgml
) would be very good. Please contact the package maintainer in order to
avoid several people working on the same manpage. You can send eletronic
mail to
.I freeciv@packages.debian.org
(this will be forwarded to the package maintainer) or visit
.I http://www.freeciv.org
and follow the instructions to join the freeciv-dev list.
.PP
.SH OPTIONS
.PP
.I civclient
accepts all of the standard X Toolkit command line options along with the
additional options listed below.
.TP 8
.BI \-help 
Show a simple help screen
.TP 8
.BI \-log " file"
Dump game-log to
.I file
.TP 8
.B \-name "playername"
Specifies name to player under. This option is critical when reconnecting
to a game.
.TP 8
.B \-port "number"
Specifies the port-number of the server.
.TP 8
.B \-server "hostname"
Specifies the address of the server.
.TP 8
.B \-version
Shows version of the client.
.SH "EXAMPLE"
.PP
civclient -name "King Richard"  -ser io.daimi.aau.dk
.SH "SEE ALSO"
.IR civserver (6)
.SH BUGS
.PP
civclient only works with the real Athena-widget-library. Linking with
Athena replacement libraries, such as Xaw3d, causes crash at runtime.
.SH "MORE INFO"
The Freeciv homepage is located at http://www.freeciv.org.
Updates and new info is first posted there.

.SH AUTHORS
     Allan Ove Kjeldbjerg - allan@daimi.aau.dk
     Claus Leth Gregersen - leth@daimi.aau.dk
     Peter Joachim Unold  - pjunold@daimi.aau.dk
