#!/bin/sh
set -e
if [ -x /usr/sbin/update-xaw-wrappers ] ; then update-xaw-wrappers ; fi
if [ -x /usr/bin/update-menus ] ; then update-menus ; fi
update-alternatives --install /usr/games/civ civ /usr/games/civclient 10 \
  --slave /usr/man/man6/civ.6.gz civ.6.gz /usr/man/man6/civclient.6.gz \
  --slave /usr/games/civ.real civ.real /usr/games/civclient.real

