#!/bin/bash

delfile() {
  echo "  Delete \"\$INSTDIR/$1\"" | sed 's,/,\\,g'
}

deldir() {
  echo "  RMDir \"\$INSTDIR/$1\"" | sed 's,/,\\,g'
}

# Generated by glib-compile-schemas.exe
delfile "share/glib-2.0/schemas/gschemas.compiled"
deldir  "share/glib-2.0/schemas"
deldir  "share/glib-2.0"
deldir  "share"

# Generated by gdk-pixbuf-query-loaders.exe
delfile "lib/gdk-pixbuf-2.0/2.10.0/loaders.cache"
deldir  "lib/gdk-pixbuf-2.0/2.10.0"
deldir  "lib/gdk-pixbuf-2.0"
deldir  "lib"

# Generated by gtk-update-icon-cache.exe
delfile "share/icons/Adwaita/icon-theme.cache"
deldir  "share/icons/Adwaita"
deldir  "share/icons"
deldir  "share"
