#ifndef _HEADER_EVENTS
#define _HEADER_EVENTS

enum {
  E_NOEVENT = -1,
  E_LOW_ON_FUNDS,
  E_POLLUTION,
  E_WARMING,
  E_CITY_DISORDER,
  E_CITY_LOVE,
  E_CITY_NORMAL,
  E_CITY_GROWTH,
  E_CITY_AQUADUCT,
  E_CITY_FAMINE,
  E_CITY_LOST,
  E_CITY_CANTBUILD,
  E_WONDER_STARTED,
  E_WONDER_BUILD,
  E_IMP_BUILD,
  E_IMP_AUTO,
  E_IMP_AUCTIONED,
  E_UNIT_UPGRADED,
  E_UNIT_BUILD,
  E_UNIT_LOST,
  E_UNIT_WIN,
  E_ANARCHY,
  E_DIPLOMATED,
  E_TECH_GAIN,
  E_DESTROYED,
  E_LAST
};

extern int message_values[E_LAST];

#endif

