/* Generated by gen_headers/generate_version_header.sh. */

#ifndef FC__VERSION_GEN_H
#define FC__VERSION_GEN_H

#define MAJOR_VERSION 3
#define MINOR_VERSION 0
#define PATCH_VERSION 92
#define EMERGENCY_VERSION 1
#ifndef VERSION_LABEL
#define VERSION_LABEL "-dev"
#endif
#ifndef VERSION_STRING
#define VERSION_STRING "3.0.92.1-dev"
#endif

#define NETWORK_CAPSTRING "+Freeciv.Devel-3.1-2020.Sep.05"

#ifndef FOLLOWTAG
#define FOLLOWTAG "S3_1"
#endif
#define FREECIV_DISTRIBUTOR ""

#endif /* FC__VERSION_GEN_H */
